"""Utility helpers for validating ARC submissions locally or in Kaggle."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable, Mapping, MutableMapping, Sequence

from predict_competition import (
    load_submission_schema,
    validate_predictions_against_schema,
)


DEFAULT_SUBMISSION = Path("submission.json")
DEFAULT_TEST_CANDIDATES: Sequence[Path] = (
    Path("arc-agi_test_challenges.json"),
    Path("data/arc-agi_test_challenges.json"),
    Path("arc-prize-2025/arc-agi_test_challenges.json"),
)


def load_json(path: Path) -> MutableMapping[str, object]:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def to_task_map(table: object) -> Mapping[str, object]:
    if isinstance(table, dict):
        return table  # already keyed by id

    result = {}
    if isinstance(table, Iterable):
        for item in table:
            if not isinstance(item, Mapping):
                continue
            task_id = item.get("task_id") or item.get("id")
            if not task_id:
                continue
            result[str(task_id)] = item.get("task") or item
    return result


def resolve_test_path(explicit: str | None) -> Path:
    if explicit:
        path = Path(explicit)
        if not path.exists():
            raise FileNotFoundError(f"ARC test challenges file not found: {path}")
        return path

    for candidate in DEFAULT_TEST_CANDIDATES:
        if candidate.exists():
            return candidate

    # Fall back to a glob search (mirrors how Kaggle datasets are mounted)
    matches = sorted(Path(".").rglob("arc-agi_test_challenges.json"))
    if matches:
        return matches[0]
    raise FileNotFoundError(
        "Unable to locate arc-agi_test_challenges.json. "
        "Set --test to point at the Kaggle ARC test JSON."
    )


def validate_submission(
    submission_path: str | Path = DEFAULT_SUBMISSION,
    test_path: str | Path | None = None,
) -> None:
    """Validate a generated submission against the ARC test manifest.

    Parameters
    ----------
    submission_path:
        Location of the JSON submission generated by the solver/notebook.
    test_path:
        Optional override for the ARC test challenges JSON. When omitted the
        function searches common Kaggle and local layouts (``data/`` as
        described in the README).
    """

    submission_path = Path(submission_path)
    if not submission_path.exists():
        raise FileNotFoundError(f"submission.json not found: {submission_path}")

    resolved_test_path = resolve_test_path(str(test_path) if test_path else None)

    submission = load_json(submission_path)
    test_blob = load_json(resolved_test_path)

    tasks = to_task_map(test_blob)
    submission_ids = set(submission.keys())
    task_ids = set(tasks.keys())

    if submission_ids != task_ids:
        missing = task_ids - submission_ids
        extra = submission_ids - task_ids
        raise AssertionError(f"Key mismatch. Missing={missing}, Extra={extra}")

    for task_id, outputs in submission.items():
        task = tasks[task_id]
        expected = len(task.get("test") or task.get("task", {}).get("test", []))
        if len(outputs) != expected:
            raise AssertionError(
                f"{task_id}: expected {expected} outputs, got {len(outputs)}"
            )

    schema = load_submission_schema()
    validate_predictions_against_schema(submission, schema.get("attempts_per_test_input", 2))

    print(
        "✅ submission.json passes strict validation!",
        f"(using {submission_path} vs. {resolved_test_path})",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate ARC submission.json")
    parser.add_argument(
        "--submission",
        default=str(DEFAULT_SUBMISSION),
        help="Path to submission.json (default: submission.json)",
    )
    parser.add_argument(
        "--test",
        default=None,
        help="Path to arc-agi_test_challenges.json. "
        "If omitted, common locations such as data/ are searched.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    validate_submission(args.submission, args.test)


if __name__ == "__main__":
    main()
